---
- name: Configure NTP Servers
  become: yes
  apt:
    name: ntp
    state: present

- name: Set NTP Servers
  become: yes
  copy:
    src: /home/ansible/playbook/roles/templetes/ntp.conf
    dest: /etc/ntp.conf
  notify:
    - Restart NTP
